### ISSUE TITLE
Create Products component

### ISSUE THREAD

**Issue by aakashindoriya** [aakashindoriya/R-W#12]
### Description
Implement the Products component to display all products and search for products.

### Tasks
- [x] Create the Products component.
- [x] Implement functionality to fetch all products.
- [x] Implement search functionality.

### Acceptance Criteria
- Products component is implemented.
- Products are fetched and displayed.
- Search functionality is working as expected.
